DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_STEP_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_STEP_EXECUTION IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_EXECUTION IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_PARAMS IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_INSTANCE IF EXISTS;

DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_STEP_EXECUTION_SEQ IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_EXECUTION_SEQ IF EXISTS;
DROP TABLE  SPRING_BATCH_SAMPLE_APP.BATCH_JOB_SEQ IF EXISTS;
